.gitignore
client/package-lock.json
client/package.json
client/src/core/router.tsx
client/src/index.tsx
client/src/server/server.ts

- 러우터, ssr 기본 뼈대 개발중
#6 
- 저희 환경에 맞춰 작동해야합니다.

[#6] ⚙ wip: 클라이언트 라우터, ssr

---

.github/auto_assign.yml

밥먹기까지 할게 마땅치 않아서 auto assign 워크플로우 추가해봤어요.
앞으로 Reviewers 등록과 Assignees 등록은 따로 안하셔도 될거에요 이 워크플로우가 잘만 동작한다면? ㅋㅋㅋ
참고로 pr을 생성해야 봇이 자동으로 등록해준다고 하네요~
closes #37 
없음

[#37] auto assign 워크플로우 추가

---

server/package-lock.json
server/package.json
server/src/entities/user.entity.ts
server/src/services/auth.service.ts

bcrypt -> bcrypt-nodejs

---

crawler/common/common.go
crawler/common/go.mod
crawler/common/go.sum
crawler/go.mod
crawler/go.sum
crawler/main.go

아.... 하긴했는데...
쿠팡 상품 상세정보는 바로 렌더링 되는게 아니라 자바스크립트로 추가동작해서 렌더링 되는 거같더라구요
그래서 http.get으로 바로 안가져와지는 부분이 있어 일단 상품 상세페이지 부분은 빠졌습니당...
서버, 프론트랑 연관없어서 완전 밖에다 빼놨어요
```
{
"id": , //메인 카테고리 아이디
"categortTitle": , // 메인 카테고리 타이틀
"mainCategoryHref": , //메인 카테고리 href
"subCategory": [
{
"subCategoryId": , //카테고리 아이디
"subCategoryTitle": , //서브 카테고리 제목
"subCategoryHref": , //서브 카테고리경로
"item": [
{
"itemHref": ,  //상품 경로
"itemTitle": ,//아이템 제목
"price": , // 가격
"contents": , // 상세내용. 이미지로 되있더라구요
"itemImages": [
{
"detailImage", // 선택된 이미지의 일반 크기 이미지
"origin", // 돋보기용 상품 확대 이미지
"preloadImage", // 상품 목록리스트에서 보여주는 이미지인 듯 합니다
"thumbnailImage",  //상세페이지에서 이미지 왼쪽 작은 이미지
}
]
}
]
}
}
```
closes #66
상세페이지 내용

데이터 크롤링 작업

---

crawler/main.go
server/src/api/routes/index.ts
server/src/entities/mainCategory.entity.ts
server/src/entities/prodectImage.entity.ts
server/src/entities/product.entity.ts
server/src/entities/subCategory.entity.ts
server/src/loaders/dataInit.ts

데이터 입력작업 완료했숩니다.
가져다 쓰기만 하면 될듯 합니다.
변경사항
- 테이블 컬럼 수정 
오타되어 있는 부분 수정하구   
필요한 컬럼 추가했습니다.
오류는 다음과 같이 있어서 수정했습니다.
1. 성인데이터 못가져옴.. (아무리 생각해도 칼라풀한 마스킹테이프가 성인용품으로 되어있는게 이해안됨.)    
- 성인상품 취급 데이터는 빼도록 설정
2. 쿠팡에는 기본적으로 헤더부분에 상품관련 정보를 넣어놓는데 일부 데이터들이 달라 잘 못가져오는 부분 수정
- 가져오는 방식 변겨엉
closes #87
- 음.... 상품 상세... 그냥 이미지 합쳐서 보여줄까요..?헿;;;;;

데이터 DB 입력 작업

---

client/src/contstants/index.ts

핫픽스로 네이밍 덜 변경된 부분 수정합니다!
closes

[#91] :bug: bug: addresses -> address

---

crawler/main.go
server/src/api/routes/product.router.ts
server/src/controllers/product.controller.ts
server/src/entities/product.entity.ts
server/src/repositories/product.repository.ts
server/src/services/product.service.ts

상세 내용은 json으로 입력되므로
데이타를 불러올때는 JSON.parse 안하셔도 됩니다 :)
contents는
details (상세 내용 이미지 또는 글)
essentials (원산지, 제조사같은 추가정보)
로 나뉘어져 있습니다.
parse가 필요합니다...
```
a = data.contents 라면
JSON.parse(a) // x 파서 안됨.
JSON.parse(a.details) // details 내용 파서 됨.
JSON.parse(a.essentials) // essentials 내용 파서 됨.
```
위와같은 형태여서 조금 번거로움이 있네요...
closes #87

상품 상세 내용 json 데이터 입력 & 실 테스트

---

client/.storybook/preview.js
client/src/components/Header/Header.stories.tsx
client/src/components/Shared/Input/Input.tsx
client/src/components/Shared/Input/style.ts
client/src/layouts/App/App.tsx
client/src/pages/SignUp/SignUp.tsx
client/src/pages/SignUp/styles.ts
client/src/pages/mypage/MyPage.stories.tsx
client/src/styles/global.scss
client/src/utils/constant/validate/validation.ts

- 인풋 컴포넌트 라벨과 에러기능을 추가했어요.
- 라벨은 labelName 파라미터를 주면 사용이 가능합니다.
- 에러는 error:boolean 과 helperText를 사용하여 에러처리를 할 수 있습니다
- 작동 예시는 스토리북 controls를 이용하거나 회원가입 페이지의 이메일 인풋을 살펴보시면 됩니다.
- 아 그리고 에러처리 
1. focusout될때마다 검사하기 
2. submit될때 검사하기
3. 각각의 인풋이 onChange될때 마다 검사하기
세가지 중에 어떤게 나을까요?
closes #82 
없는 것 같은데 혹시 모를 인풋 에러가 나면 추가 구현이 필요할 것 같습니다!

인풋 컴포넌트 라벨 기능 및 에러 기능 추가

---

server/src/api/routes/cart.router.ts
server/src/api/routes/index.ts
server/src/controllers/cart.controller.ts
server/src/entities/cart.entity.ts
server/src/repositories/cart.respository.ts
server/src/services/cart.service.ts

- cart 추가/조회/삭제 api 추가합니다.
- 위키에 api 문서 남길게요
closes #115 
- 유저 아이디 사용

cart 추가/조회/삭제 api

---

server/src/controllers/cart.controller.ts
server/src/entities/product.entity.ts
server/src/entities/productImage.entity.ts
server/src/loaders/dataInit.ts
server/src/repositories/cart.respository.ts
server/src/services/cart.service.ts

- 카트/상품/상품 이미지 조인 로직 추가
- 불필요한 페이로드를 제거
- 오타 수정
#115 
- client 연동 (pr이 커질 거 같아 서버로직 먼저 올립니다!)

오타 수정 및 카트/상품/상품 이미지 조인 로직 추가

---

client/package-lock.json
client/src/components/Header/Search/Search.tsx
client/src/lib/Router.tsx
server/package-lock.json
server/package.json
server/src/api/routes/product.router.ts
server/src/config/index.ts
server/src/controllers/cart.controller.ts
server/src/controllers/product.controller.ts
server/src/entities/product.entity.ts
server/src/entities/productImage.entity.ts
server/src/loaders/dataInit.ts
server/src/loaders/elasticSearch.ts
server/src/repositories/cart.respository.ts
server/src/repositories/product.repository.ts
server/src/services/cart.service.ts
server/src/services/product.service.ts

env 경로에 
ELASTIC_HOST=http://localhost:9200/ 추가해야됩니다.
Dev일 경우 우리 호스팅 http://3.38.92.37:9200/ 로 추가하면됩니다
지금은 모든포트가 개방되어있는데 
정해진 ip의 형태로 개방을 변경해야 할듯합니다.
pr 올리고 서버 env 가서 수정하겟숩니다
가져오는데이터는
id
title
price
image
이렇게 4개 가져옵니다 !
헤더에는 테스트수준으로만 코드를 작성해 두었고 
디자인 적인 부분 또는 추가 필요사항부분은 개선해나가겠습니다.
closes #89
프론트 헤더 추가 구현

엘라스틱 서치 적용

---

client/src/components/Shared/Input/Input.tsx
client/src/hooks/useInput.tsx
client/src/lib/api/login/githubLogin.ts
client/src/pages/Approval/Approval.tsx
client/src/pages/Login/Login.tsx
client/src/pages/SignUp/SignUp.tsx
client/src/utils/constant/validate/validation.ts
server/package-lock.json
server/package.json
server/src/api/middlewares/api.ts
server/src/api/middlewares/invalid-request.ts
server/src/api/middlewares/response-format.ts
server/src/api/routes/index.ts
server/src/api/routes/user.router.ts
server/src/controllers/user.controller.ts
server/src/core/error.ts
server/src/dtos/user/check.ts
server/src/types/statusCode.ts

- 회원가입 클라이언트 에러처리 구현
- 서버 유저 중복확인 체크 api 구현
- 서버 api validation구현
- 서버 api response format 구현
- 서버 api Error middleware 구현
어쩌다 보니 서버 포맷팅 작업이 많이 들어갔네요..
사용하다가 불편함이 느껴지면 과감하게 구조 변경 제안해주시면 좋을 것 같습니다!
아 그리고 메시지 상수화는 validation이랑 send message정도로 크게 나누면 좋을 것 같습니다. 각각의 라우터로 폴더구조를 나누면 되려나요 상수화도 ..
#111 
- 회원가입 중복확인 연동
- 회원가입 api 만들기
- github회원가입 이름 error처리

회원가입 클라이언트 에러처리 구현, 서버 유저 중복확인 체크 api 기타등등..

---

client/src/components/MyPage/OrderHistory/OrderHistory.tsx
client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
client/src/components/ShoppingCart/ShopingCartItem/ShopingCartItem.tsx
client/src/components/ShoppingCart/ShoppingCartList/ShoppingCart.stories.tsx
client/src/components/ShoppingCart/ShoppingCartList/ShoppingCartList.tsx
client/src/dummies/orderHistory.ts
client/src/hooks/queries/cart/index.tsx
client/src/lib/api/cart/index.ts
client/src/pages/ShoppingCart/ShoppingCart.tsx
client/src/types/index.ts
server/src/api/routes/cart.router.ts
server/src/controllers/cart.controller.ts
server/src/repositories/cart.respository.ts
server/src/services/cart.service.ts

- 장바구니 프론트 타입 변경 
- 장바구니 react-query hooks 추가
- 장바구니 api 추가
closes #115 
- 우리가 서버에서 message를 내려주고 있는데, react-query 사용하면 사용을 안 할 거 같기도 하구요...!? 더 찾아봐야 할 거 같아요!

장바구니 api 연동

---

client/package-lock.json
client/package.json
client/src/components/MyPage/OrderHistory/OrderHistory.tsx
client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.stories.tsx
client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
client/src/components/Shared/Error/Error.stories.tsx
client/src/components/Shared/Error/Error.tsx
client/src/components/Shared/Error/index.tsx
client/src/components/Shared/Error/styles.ts
client/src/components/Shared/Loading/Loading.stories.tsx
client/src/components/Shared/Loading/Loading.tsx
client/src/components/Shared/Loading/index.tsx
client/src/components/Shared/Loading/styles.ts
client/src/dummies/orderHistory.ts
client/src/index.tsx
client/src/layouts/App/App.tsx
client/src/lib/api/cart/index.ts
client/src/lib/api/login/githubLogin.ts

- 서스펜션을 이용한 비동기 데이터 로딩 및 에러를 처리하도록 구조 설계 및 컴포넌트 작성
- OrderItemList 파일명 겹치는 부분 수정
closes #135 
- 에러 및 로딩 컴포넌트 세부 디자인

로딩 및 에러 컴포넌트 서스펜스 연계하여 작성

---

client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
client/src/lib/api/cart/index.ts
client/src/pages/ShoppingCart/ShoppingCart.tsx

OrderItem type 수정, api 요청 경로에서 'api' 제외

---

client/package-lock.json
client/package.json
client/src/components/Shared/Collapse/Collapse.tsx
client/src/components/Shared/Modal/Portal/Portal.tsx
client/src/components/Shared/Toastify/Portal.tsx
client/src/components/Shared/Toastify/ToastifyContainer.tsx
client/src/components/Shared/Toastify/index.tsx
client/src/components/Shared/Toastify/notify.tsx
client/src/hooks/queries/cart/index.tsx
client/src/index.html
client/src/index.tsx

- Portal을 이용해 ToastifyContainer를 최상단에 선언합니다.
- nofity 메서드를 통해 해당하는 타입의 메시지창을 띄울 수 있습니다.
- 사용법은 Wiki에 문서화 하도록 할게요~ 매우 간단합니당
- 사용방법 [Wiki](https://github.com/woowa-techcamp-2021/store-10/wiki/%EC%BB%A4%EC%8A%A4%ED%85%80-%ED%86%A0%EC%8A%A4%ED%8A%B8UI)
closes #137 
- 필요시 디자인 & 위치조정

toastify 컴포넌트 작성

---

server/src/controllers/order.controller.ts
server/src/entities/order.entity.ts
server/src/entities/product.entity.ts
server/src/entities/user.entity.ts

- purchase table 
- order table로 이름 변경
closes
진짜는 아직 시작도 안함..ㅎㅎ

refactor: purchase table -> order table

---

client/src/components/ProductDetails/ProductDescription/ProductDescription.tsx
client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
client/src/hooks/queries/cart/index.tsx
client/src/hooks/queries/product/index.tsx
client/src/index.tsx
client/src/layouts/App/App.tsx
client/src/lib/api/cart/index.ts
client/src/lib/api/client.ts
client/src/lib/api/login/githubLogin.ts
client/src/lib/api/login/normalLogin.ts
client/src/lib/api/product/index.ts
client/src/lib/api/product/searchData.ts
client/src/lib/api/user/createUser.ts
client/src/lib/api/user/getCurrentUser.ts
client/src/lib/api/user/postEmailCheck.ts
client/src/pages/Main/Main.tsx
client/src/pages/ShoppingCart/ShoppingCart.tsx
client/src/types/index.ts
server/src/api/middlewares/checkUser.middleware.ts
server/src/api/middlewares/response-format.ts
server/src/controllers/auth.controller.ts
server/src/controllers/cart.controller.ts
server/src/controllers/product.controller.ts
server/src/controllers/user.controller.ts

- response type 변경
- 클라이언트 에러 핸들링
- api 관련 에러는 react-query가 핸들링 합니다!
- 그 외에 전역 에러는 모두 suspense가 핸들링합니다!
- ApiResponse success param 제거
변경 사항이 많은데, 대부분 타입 수정이라 아래 부분을 중점적으로 보시면 될 거 같아요. 
- types/index.ts, 
- controller에서 ApiResponse 호출하는 부분
- lib/api/client
- hooks/queries
- 
closes #155 

[#157] :sparkles refactor: response type 관련 수정

---

client/package.json
client/src/components/Header/Search/Search.tsx
client/src/components/Header/Sidebar/Sidebar.tsx
client/src/components/Shared/Input/Input.tsx
client/src/hooks/queries/product/index.tsx
client/src/layouts/App/App.tsx
client/src/lib/api/category/index.ts
client/src/lib/api/product/index.ts
client/src/lib/api/product/searchData.ts
client/src/pages/Category/Category.stories.tsx
client/src/pages/Category/Category.tsx
client/src/pages/Category/index.tsx
client/src/pages/Category/styles.ts
client/src/types/index.ts
server/src/api/routes/product.router.ts
server/src/controllers/product.controller.ts
server/src/entities/mainCategory.entity.ts
server/src/entities/product.entity.ts
server/src/entities/subCategory.entity.ts
server/src/loaders/dataInit.ts
server/src/repositories/mainCategory.repository.ts
server/src/repositories/subCategory.repository.ts
server/src/repositories/user.repository.ts
server/src/services/product.service.ts
server/src/utils/combineObjectArray.ts

1. 메인카테고리 오타난 부분 수정되어있어서 먼저 pr 올립니다 !
2. 카테고리 받아오는 api추가
3. objectcombine 유틸 추가
closes

카테고리 페이지 관련 사항 내용 추가

---

server/ormconfig.ts
server/src/api/middlewares/validation/bookmark/deleteBookmarks.ts
server/src/api/middlewares/validation/bookmark/getBookmark.ts
server/src/api/routes/bookmark.router.ts
server/src/api/routes/index.ts
server/src/controllers/bookmark.controller.ts
server/src/entities/bookmark.entity.ts
server/src/repositories/bookmark.repository.ts
server/src/services/bookmark.service.ts

- 유저 북마크 리스트 가져오기 api 구현
- 유저 북마크 상세 리스트 가져오기 api 구현
- 유저 북마크 등록 api 구현
- 유저 북마크 삭제 api 구현
#167 
찜 목록 마크업
찜 목록 마크업 및 상품 찜 버튼과 연동
백엔드라 스크린샷은 없어요~ 포스트맨 참조!

북마크 api 구현

---

client/src/components/Order/OrderAddress/OrderAddress.tsx
client/src/components/Order/OrderAddress/index.tsx
client/src/components/Order/OrderAddress/styles.ts
client/src/components/Order/OrderCoupon/OrderCoupon.tsx
client/src/components/Order/OrderCoupon/index.ts
client/src/components/Order/OrderCoupon/styles.ts
client/src/components/Order/OrderPayment/OrderPayment.tsx
client/src/components/Order/OrderPayment/index.tsx
client/src/components/Order/OrderPayment/styles.ts
client/src/components/Order/OrderProducts/OrderProducts.tsx
client/src/components/Order/OrderProducts/index.tsx
client/src/components/Order/OrderProducts/styles.ts
client/src/components/Order/OrderSummary/OrderSummary.tsx
client/src/components/Order/OrderSummary/index.tsx
client/src/components/Order/OrderSummary/styles.ts
client/src/components/Order/styles.ts
client/src/pages/Order/Order.tsx
client/src/pages/Order/index.tsx
client/src/pages/Order/styles.ts

- 주문 결제 페이지 마크업입니다!
- pr이 너무 커져서 4개로 나눴습니다! pr마다 가장 마지막 커밋으로 봐주시면 됩니다 🙇🙇  죄송합니다..!
#170 
- 쿠폰, 결제수단 마크업

주문 페이지 마크업 [주문 1]

---

client/src/components/Order/OrderAddress/OrderAddress.tsx
client/src/components/Order/OrderAddress/index.tsx
client/src/components/Order/OrderAddress/styles.ts
client/src/components/Order/OrderCoupon/OrderCoupon.tsx
client/src/components/Order/OrderCoupon/index.ts
client/src/components/Order/OrderCoupon/styles.ts
client/src/components/Order/OrderPayment/OrderPayment.tsx
client/src/components/Order/OrderPayment/index.tsx
client/src/components/Order/OrderPayment/styles.ts
client/src/components/Order/OrderProducts/OrderProducts.tsx
client/src/components/Order/OrderProducts/index.tsx
client/src/components/Order/OrderProducts/styles.ts
client/src/components/Order/OrderSummary/OrderSummary.tsx
client/src/components/Order/OrderSummary/index.tsx
client/src/components/Order/OrderSummary/styles.ts
client/src/components/Order/styles.ts
client/src/components/Shared/Select/Select.tsx
client/src/components/Shared/Select/index.ts
client/src/components/Shared/Select/styles.ts
client/src/pages/Order/Order.tsx
client/src/pages/Order/index.tsx
client/src/pages/Order/styles.ts

- 공통으로 사용할 셀렉트 컴포넌트 입니다
- pr이 너무 커져서 4개로 나눴습니다! pr마다 가장 마지막 커밋으로 봐주시면 됩니다 🙇🙇  죄송합니다..!
closes
- 스토리북 아직 추가 못했어요!

Select component 추가 [주문 2]

---

client/src/components/Card/Card.stories.tsx
client/src/components/Card/Card.tsx
client/src/components/Card/styles.ts
client/src/components/CardWrapper/CardWrapper.stories.tsx
client/src/components/CategorySelector/CategorySelector.stories.tsx
client/src/components/MyPage/MyPageAside/styles.ts
client/src/components/MyPage/OrderHistory/styles.ts
client/src/components/Order/OrderProducts/styles.ts
client/src/components/Shared/Spinner/Spinner.stories.tsx
client/src/components/Shared/Spinner/Spinner.tsx
client/src/components/Shared/Spinner/index.tsx
client/src/components/Shared/Spinner/styles.ts
client/src/components/ShoppingCart/ShopingCartItem/styles.ts
client/src/components/ShoppingCart/ShoppingCartSummary/styles.ts
client/src/components/Skeleton/CardSkeleton/CardSkeleton.stories.tsx
client/src/components/Skeleton/CardSkeleton/CardSkeleton.tsx
client/src/components/Skeleton/CardSkeleton/index.tsx
client/src/components/Skeleton/CardSkeleton/styles.ts
client/src/components/Skeleton/LoadingCards/LoadingCards.tsx
client/src/components/Skeleton/LoadingCards/index.tsx
client/src/pages/Main/Main.tsx
client/src/pages/Mypage/styles.ts
client/src/styles/styled.d.ts
client/src/styles/theme.ts

- 스켈레톤 컴포넌트를 추가했습니다. 실제로 잘 보이진 않네요 ㅋㅋㅋㅋ 로딩이 워낙빨라서
- 배경색을 white로 변경했습니다. 이전에 칙칙한 느낌이 있던 거를 바꿨어요 이부분에서 컴포넌트 색상이 흰색이라면 컴포넌트 색상을 조금 바꿔야할것같기도 하네요.
- 공통 박스 쉐도우를 추가했습니다. theme.shadow로 쓰시면 됩니다!
- 스피너 컴포넌트 추가 아마 이것도 크기조절은 커스텀으로 하시면 될 것 같아요!
뭔가 스켈레톤작업하면서 css를 간단하게만 바꿨는데도 인상이 확달라지는군요..
꿀팁이 저희가 예전에 했던 기획서에서 컴포넌트 디자인 끌고 오면 뭔가 세련되보여요..ㅋㅋㅋ 앞으로 많이 끌고 옵시당~!
closes #158
- 스피너
- 인피니티 스크롤

스켈레톤 컴포넌트 추가 및 적용 및 공통 박스 쉐도우 추가 및 배경색 white로 변경

---

client/src/components/CategorySelector/CategorySelector.tsx
client/src/components/Header/Header.tsx
client/src/components/MyPage/OrderHistory/OrderHistory.tsx
client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.stories.tsx
client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.tsx
client/src/components/MyPage/OrderHistory/OrderItemList/styles.ts
client/src/components/Shared/Modal/RequestModal.tsx
client/src/contstants/index.ts
client/src/dummies/orderHistory.ts
client/src/hooks/queries/order/index.tsx
client/src/lib/api/order/index.ts
client/src/types/index.ts
client/src/utils/helper.ts
server/src/controllers/order.controller.ts
server/src/entities/order.entity.ts
server/src/repositories/order.repository.ts
server/src/services/order.service.ts

- 주문 내역 데이터 바인딩
- 주문 내역 필터링 수정
- 주문 내역 페이지네이션
- 데이터 구조에 맞게 주문 내역 타입, 스타일 수정
closes
- 주문내역 공용 텅 추가

주문내역 프론트 api 연동

---

server/src/api/routes/cart.router.ts
server/src/controllers/cart.controller.ts
server/src/controllers/order.controller.ts
server/src/repositories/cart.respository.ts
server/src/services/cart.service.ts

장바구니 중복 추가하면 장바구니 갯수만 올라가도록 처리합니다!
closes #200
x

장바구니 중복 추가

---

client/src/components/CategoryProducts/CategoryProducts.tsx
client/src/components/SearchProducts/SearchProducts.tsx
client/src/hooks/queries/product/index.tsx
client/src/lib/api/client.ts
client/src/lib/api/product/index.ts
server/src/controllers/product.controller.ts
server/src/loaders/express.ts
server/src/repositories/product.repository.ts
server/src/services/product.service.ts

1. 검색페이지 인피니티 스크롤
2. 카테고리 페이지 인피니티스크롤 60개 제한한거 리팩토링
3. express loader cors 크로마틱 추가
closes

168 [feat] 카테고리/상품검색 페이지

---

client/src/components/MyPage/OrderHistory/OrderHistory.tsx
client/src/components/MyPage/OrderHistory/styles.ts
client/src/components/Order/OrderPayment/OrderPayment.tsx
client/src/components/Order/OrderPayment/styles.ts
client/src/components/Order/OrderSummary/OrderSummary.tsx
client/src/components/Order/OrderSummary/styles.ts
client/src/components/ShoppingCart/ShoppingCartSummary/ShoppingCartSummary.tsx
client/src/hooks/queries/order/index.tsx
client/src/layouts/App/App.tsx
client/src/lib/api/order/index.ts
client/src/pages/Order/Order.tsx
client/src/pages/Order/Paid/Paid.stories.tsx
client/src/pages/Order/Paid/Paid.tsx
client/src/pages/Order/Paid/index.tsx
client/src/pages/Order/Paid/styles.ts
client/src/types/index.ts
server/src/repositories/order.repository.ts

- 주문 관련 케쉬 문제 버그 해결
- 결제 완료 페이지 추가
- 결제 수단 UI 추가
- 결제 동의 UI 추가
closes #210 
- 결제시 쿠폰, 할인 적용

결제 관련 UI 추가

---

client/src/components/MyPage/MyReviews/MyReviews.tsx
client/src/components/MyPage/MyReviews/styles.ts
client/src/components/Shared/Input/FileInput.tsx
client/src/components/Shared/Modal/ReviewModal/ReviewUpdateModal.stories.tsx
client/src/components/Shared/Modal/ReviewModal/ReviewUpdateModal.tsx
client/src/components/Shared/Modal/index.tsx
client/src/components/Shared/Rating/RatingSetter.tsx
client/src/hooks/queries/product/index.tsx
client/src/hooks/useFileInput.tsx
client/src/lib/api/client.ts
client/src/lib/api/product/index.ts
server/src/api/routes/product.router.ts
server/src/controllers/product.controller.ts
server/src/entities/question.entity.ts
server/src/repositories/review.repository.ts
server/src/repositories/reviewImage.repository.ts
server/src/services/product.service.ts

- 리뷰 탭 수정 기능 연동
- 별점 / 텍스트 내용 수정 가능
- 이미지 재업로드 가능
- 이미 업로드 된 이미지 제거 가능
- 이미지 건드리지 않고 그대로 제출 가능
closes #213 
- 듸좌인?

마이페이지 리뷰탭 마무으리

---

client/src/components/Shared/Collapse/Collapse.tsx
client/src/types/index.ts
server/src/entities/user.entity.ts
server/src/repositories/question.repository.ts

- 기존 user.name으로 일치여부를 확인하던 로직에서 고유값인 user_id로 확인하도록 변경했습니다.
- User table 쿠폰 컬럼 문제로 잠시 주석처리했습니다
closes #208 
- 없음

비밀글 열람 조건 변경

---

client/.storybook/preview.js
client/src/components/MyPage/ChangeUserInfo/ChangeUserInfo.tsx
client/src/components/MyPage/ChangeUserInfo/index.tsx
client/src/components/MyPage/ChangeUserInfo/styles.ts
client/src/components/MyPage/MyPageAside/MyPageAside.tsx
client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
client/src/components/Shared/Input/Input.tsx
client/src/contstants/index.ts
client/src/lib/api/auth/passwordCheck.ts
client/src/lib/api/user/changeNickName.ts
client/src/lib/api/user/changePassword.ts
client/src/pages/Mypage/MyPage.tsx
client/src/types/index.ts
server/src/api/middlewares/auth.middleware.ts
server/src/controllers/auth.controller.ts
server/src/controllers/user.controller.ts
server/src/entities/user.entity.ts
server/src/services/auth.service.ts

- 기존에 토큰에 저장되는 정보중 is_oauth를 추가하였습니다.
- 유저 쿠폰 정보 엔티티 삭제
- 마이페이지 유저 정보 변경 (닉네임, 비밀번호) 깃허브는 닉네임만 변경가능 하는 섹션 추가
- 상세페이지 찜 기능 추가
closes #212 
없는 것 같습니다

마이 페이지 유저 정보 변경 기능 추가

---

client/src/components/MyPage/MyCoupon/MyCoupon.stories.tsx
client/src/components/MyPage/MyCoupon/MyCoupon.tsx
client/src/components/MyPage/MyCoupon/index.tsx
client/src/components/MyPage/MyCoupon/styles.ts
client/src/components/MyPage/MyPageAside/MyPageAside.stories.tsx
client/src/components/MyPage/MyQuestions/MyQuestion.stories.tsx
client/src/components/MyPage/MyReviews/MyReviews.stories.tsx
client/src/components/MyPage/OrderHistory/OrderHistory.stories.tsx
client/src/components/MyPage/OrderHistory/OrderItemList/OrderItemList.stories.tsx
client/src/components/Shared/Coupon/Coupon.stories.tsx
client/src/components/Shared/Coupon/Coupon.tsx
client/src/components/Shared/Coupon/index.tsx
client/src/components/Shared/Coupon/styles.ts
client/src/pages/Mypage/MyPage.tsx

- 쿠폰 컴포넌트 재사용 가능하게 작성 (유효/비유효 구분 + 쿠폰 이름 + 할인율 지정)
- 마이페이지 쿠폰탭 작성
closes #226 
- API 연결
- 회원가입 시 쿠폰 등록
- 구매 시 쿠폰 적용 (적용 시 할인율 만큼 금액 차감)
- 사용 시 쿠폰 사용 체크
- 쿠폰 조회 API

쿠폰 탭 및 쿠폰 컴포넌트 작성

---

client/src/components/CategorySelector/styles.ts
client/src/components/ProductDetails/ProductReview/ProductReview.tsx
client/src/components/Shared/Collapse/Collapse.tsx
client/src/components/Shared/Collapse/styles.ts
client/src/components/Shared/Form/styles.ts
client/src/components/Shared/Input/FileInput.tsx
client/src/components/Shared/Input/NumberInput.tsx
client/src/components/Shared/Input/style.ts
client/src/components/Shared/Modal/RequestModal/RequestModal.tsx
client/src/components/Shared/Modal/RequestModal/RequestUpdateModal.tsx
client/src/components/Shared/Modal/ReviewModal/ReviewModal.tsx
client/src/components/Shared/Modal/ReviewModal/ReviewUpdateModal.tsx
client/src/components/Shared/Modal/styles.ts
client/src/hooks/useNumberInput.tsx
client/src/lib/api/order/index.ts
client/src/styles/globalStyle.ts
client/src/types/index.ts
server/src/api/routes/order.router.ts
server/src/controllers/order.controller.ts
server/src/repositories/order.repository.ts
server/src/services/order.service.ts

- 상품 구매 후에만 리뷰 작성 가능하도록 수정
- 소수점 입력 방지
- 비공개 문의 본인 열람 불가하던 점 수정
- 일부 반응형 디자인 적용안 된 부분 적용
closes #304 closes #301 closes #292
- 추가 제보 사항에 리뷰 중복 안건이 있었으나, 크게 중요하지 않다고 생각하여 적용하지 않고 종료했습니다.

리뷰 및 상세페이지 관련 버그 해결 및 반응형 디자인 미비한 부분 보충

---

client/src/hooks/useGlobalTheme.tsx

아이고 죄송합니당;;;
텍스트 상수로 빼는과정에서 다크모드 부분을 빼먹엇군요;;;;
closes

🐛 bug: 다크모드 변경 안되는 것 수정

---

client/src/pages/Order/Paid/styles.ts
client/src/styles/globalStyle.ts

- 오 매우 간단하게 다크 모드 추가,,,!
closes #319 

결제완료 반응형/다크모드

---

client/src/components/Address/AddressForm/styles.ts
client/src/components/Address/styles.ts
client/src/components/Order/OrderAddress/styles.ts
client/src/components/Order/OrderCoupon/OrderCoupon.tsx
client/src/components/Order/OrderCoupon/styles.ts
client/src/components/Order/OrderPayment/styles.ts
client/src/components/Order/OrderProducts/styles.ts
client/src/components/Order/OrderSummary/OrderSummary.tsx
client/src/components/Order/OrderSummary/styles.ts
client/src/components/Shared/Modal/AddressModal/AddressModal.tsx
client/src/components/Shared/Modal/AddressModal/styles.ts
client/src/components/Shared/Select/styles.ts
client/src/pages/Order/styles.ts
client/src/styles/globalStyle.ts
client/src/styles/styled.d.ts

- 결제 페이지 반응형/다크모드 작업
- 쿠폰은 킹열님 이슈랑 겹칠거 같아서 우선 비워뒀습니다!
#312 
- 쿠폰 반응형

결제 페이지 반응형/다크모드

---

client/src/components/Order/OrderCoupon/OrderCoupon.tsx
client/src/components/Order/OrderCoupon/styles.ts
client/src/components/Shared/Coupon/styles.ts
client/src/components/Shared/Modal/CouponModal/CouponModal.stories.tsx
client/src/components/Shared/Modal/CouponModal/CouponModal.tsx
client/src/components/Shared/Modal/CouponModal/index.ts
client/src/components/Shared/Modal/CouponModal/styles.ts
client/src/pages/Order/Paid/Paid.tsx

- 결제 페이지 쿠폰 반응형 작업... 똥꼬쇼 하다가 결국 쿠폰 선택 모달을 넣었습니다...ㅎㅎ
- 배송 조회 gif 케쉬되면 안 나오는 버그가 있어서 매번 갱신하도록 수정했습니다.
closes #312
- 진짜 끝..?

결제 쿠폰 반응형, 배송 버그 수정

---

client/src/components/Header/Search/SearchItem/style.ts
client/src/components/Header/Search/styles.ts
client/src/components/Header/Sidebar/styles.ts
client/src/components/Header/styles.ts
client/src/components/Shared/Collapse/Collapse.tsx
client/src/components/Shared/Collapse/styles.ts
client/src/pages/Notice/Notice.tsx
client/src/pages/Notice/styles.ts
client/src/pages/Terms/styles.ts
client/src/pages/Vendor/Vendor.tsx
client/src/pages/Vendor/styles.ts

1. 판매처 url word-break안되는 오류 수정
2. 다크모드 글자색 text-color 안되어있는 부분 수정
3. 공지사항 태블릿 미만 작성자, 작성일자 사라지는 오류 수정
4. 콜랩스 공지사항용 클래스 추가
5. 모바일 사이드바 반응형 추가
6. 헤더 검색바 가운데 정렬
closes #289
끝.??

289 [design] 공지사항, 이용약관. 개인정보, 판매처안내 및 푸터 페이지 반응형 및 다크모드

---

client/src/components/Shared/Modal/DeliveryModal/DeliveryModal.tsx

[#312]  :bug: bug: 배달 gif 갱신

---

client/src/components/MyPage/MyQuestions/MyQuestions.tsx
client/src/components/MyPage/MyReviews/MyReviews.tsx
client/src/components/ProductDetails/ProductInfo/ProductInfo.tsx
client/src/components/Shared/Coupon/Coupon.tsx
client/src/components/Shared/Coupon/styles.ts
client/src/components/Shared/Modal/CouponModal/CouponModal.tsx
client/src/components/Shared/Modal/CouponModal/styles.ts
client/src/components/Skeleton/ProductSkeleton/InfoSkeleton.tsx

- 전체적인 디자인 통일 완료
closes #329 closes #274
> 이젠 나도 미씨온 해야지~~

전체적인 페이지 디자인 점검(완)

---

client/src/components/Header/Search/Search.tsx
client/src/components/Header/Sidebar/Sidebar.tsx
client/src/components/Shared/Modal/MissionModal/MissionModal.tsx
client/src/contstants/index.ts
client/src/types/index.ts

검색 & 카테고리 이동 미션

---

client/src/hooks/queries/coupon/index.ts

 발급된 쿠폰이 케쉬되지 않도록 합니다.
